name: Continuous Integration

on: pull_request

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    container: php:8.2-apache

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: composer install --no-interaction --no-progress --prefer-dist

      - name: Run PHPUnit Tests
        run: ./vendor/bin/phpunit
